// <auto-generated />
namespace EFCodeFirstApproach.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class InsertqueryforDeptTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InsertqueryforDeptTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202102120540268_Insert query for Dept Table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
